# Generated by Django 4.1.7 on 2023-03-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
