# Generated by Django 4.2.1 on 2023-05-05 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_profile_age_alter_user_profile_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=150, null=True)),
                ('shop_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shop_mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=150, null=True)),
                ('lng', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('ciy', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop_profile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop_profile',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user_profile'),
        ),
    ]
