# Generated by Django 4.2.1 on 2023-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_shop_profile_delete_shop_customuser_is_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_profile',
            name='shop_image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
