# Generated by Django 4.2.1 on 2023-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_shop_profile_shop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_profile',
            old_name='ciy',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='shop_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
